name: Build and Release Chrome Extension

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # install yarn
      - name: Install yarn
        run: npm i -g yarn

      # Install dependencies (if using npm or yarn)
      - name: Install dependencies
        run: |
          yarn install

      # Build the extension (if using a build tool like Webpack)
      - name: Build extension
        run: |
          yarn build

      # Package the extension into a ZIP file
      - name: Package extension
        run: |
          mkdir -p release
          mv dist/*.zip release/

      # Upload the ZIP file as a release asset
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: release/*.zip
